### ISSUE TITLE
Error RandomForestClassifier

### ISSUE THREAD

**Issue by lezzidan** [bsc-wdc/dislib#109]
I have this error with all the scripts of classifiers

bscthunderbolt:dislib lezzi$ dislib exec rf_iris.py
Executing cmd: runcompss          --lang=python         --python_interpreter=python3         --project=/project.xml         --resources=/resources.xml         rf_iris.py
[  INFO] Using default execution type: compss

----------------- Executing rf_iris.py --------------------------

WARNING: COMPSs Properties file is null. Setting default values

[(861)    API]  -  Starting COMPSs Runtime v2.4.rc1812 (build 20181218-1519.rbae7e52ba7661f0bdeb89f345c8bcde3ae7ff4e7)
[(4433)    API]  -  Execution Finished
Traceback (most recent call last):
File "/opt/COMPSs/Bindings/python/3/pycompss/runtime/launch.py", line 638, in <module>
compss_main()
  File "/opt/COMPSs/Bindings/python/3/pycompss/runtime/launch.py", line 165, in compss_main
exec (compile(open(app_path).read(), app_path, 'exec'), globals())
  File "rf_iris.py", line 3, in <module>
from dislib.classification import RandomForestClassifier
ImportError: cannot import name 'RandomForestClassifier'
Error running application

**Comment by javicid** [comment]
Try running `dislib init` in the dislib directory (where the sources are), and then run `dislib exec examples/rf_iris.py`

**Comment by lezzidan** [comment]
Ok it works
