### ISSUE TITLE
Automate creation of release packages

### ISSUE THREAD

**Issue by kafkasl** [bsc-wdc/dislib#115]
The travis build should package a dislib_latest.tar.gz and upload it to github or something similar.

Basically, otherwise we have no way of having a 'latest' release and we will end up having desynch versions between the downloaded release (e.g. v0.1.0) and a fresh clone (as indicated in the README.md in run an example).

**Comment by javicid** [comment]
We could treat the latest source code available as an "unstable" version of the library, and use the latest release for everything. We can create new releases as often as necessary to incorporate new developments and bug fixes.
