### ISSUE TITLE
Travis: enable access to logs after failure

### ISSUE THREAD

**Issue by salvisolamartinell** [bsc-wdc/dislib#186]
**Is your feature request related to a problem? Please describe.**
Occasionaly, the tests fail on travis-ci jobs and there is no way to reproduce the errors or get the logs to find the problem.

**Describe the solution you'd like**
I'd like to be able to access the logs after the tests fail on a travis job.

**Describe alternatives you've considered**
On the after_failure step, we could send the logs to a file-sharing service. [Transfer.sh](https://transfer.sh) could be used, so following a link from the output would be enough. AmazonS3 is another option.

**Comment by kafkasl** [comment]
All the logs available are printed after executing the tests, so if there is some error you can see it there. Is it not working or do you have some issue with that?

**Comment by salvisolamartinell** [comment]
Oh, that's true! I didn't know I could see them expanding the line:
> docker exec dislib /dislib/bin/print_tests_logs.sh
Thank you, closing the issue.
