### ISSUE TITLE
Create a minimal example of how to use K-means, DBSCAN and C-SVM

### ISSUE THREAD

**Issue by javicid** [bsc-wdc/dislib#21]

**Comment by kafkasl** [comment]
More details are needed. Aren't there already the sklearn-style examples with both clustering and classfication?

**Comment by javicid** [comment]
@kafkasl these examples might be too complex for first time users. We should also provide very simple usage examples of the algorithms, maybe as part of the documentation.

**Comment by kafkasl** [comment]
@javicid I agree. Do you have the 4 lines you showed yestereday as demo? If you paste them here I'll add them and see if they look good as part of the documentation.

**Comment by javicid** [comment]
@kafkasl Sorry, I didn't get notified about this. Which lines do you mean?

**Comment by kafkasl** [comment]
@javicid the ones you presented in the weekly meeting! but now with the new tests there are plenty of examples, no need to worry
