### ISSUE TITLE
Remove pandas dependency

### ISSUE THREAD

**Issue by kafkasl** [bsc-wdc/dislib#211]
Pandas package is used to load data for the ALS dataset. Remove the dependency by loading data manually in `test_als.py`

**Comment by sravyasri** [comment]
@kafkasl  Can I pick this up? #hacktoberfest

**Comment by javicid** [comment]
@sravyasri yes, of course!

**Comment by sravyasri** [comment]
@javicid can you provide me the docker image? I don't see it in the quickstart guide!

**Comment by javicid** [comment]
@sravyasri you can find the image in docker hub: https://hub.docker.com/r/bscwdc/dislib
