### ISSUE TITLE
FFT memory error

### ISSUE THREAD

**Issue by kafkasl** [bsc-wdc/dislib#212]
The fft implementation raises a MemoryError exception for an audio file of size 4137056. The exception is raised when trying to allocate memory for `w`:
```
~/repos/dislib/dislib/fft/base.py in fft(a)
     28 
     29     # precompute twiddle factors
---> 30     w = np.zeros((n, n), dtype=complex)
     31 
     32     for i in range(n):

MemoryError: 
```

**To Reproduce**

Minimal example code

```
audio_input = np.array([0 for _ in range(4137056)])
audio_fft2 = fft(audio_input)
```

**Expected behavior**

Using fftpack implementation causes no error and finishes successfully in 1.69 s ± 59 ms (for the all-0 example):

```
audio_input = np.array([0 for _ in range(4137056)])
audio_fft = fftpack.fft(audio)                                                                                 
```

**Comment by javicid** [comment]
Closing because FFT is no longer in the library. We can add it again in the future if someone needs it.
