### ISSUE TITLE
Array slicing by list of indices

### ISSUE THREAD

**Issue by salvisolamartinell** [bsc-wdc/dislib#235]
**Describe the bug**
Array slicing by list of indices fails in some cases.

**To Reproduce**

Minimal example code

```
import dislib
b = dislib.array([[1,2,3,4],[5,6,7,8],[9,10,11,12], [13,14,15,16], [17,18,19,20]],(3,3))
b[[0,1,2,3]]
```

**Expected behavior**
`b[[0,1,2,3]].collect()` should be equal to `b[0:4].collect()`

**Environment (please complete the following information):**
 - COMPSs version: 2.5
 - Dislib version: master

**Comment by salvisolamartinell** [comment]
Also, for sparse arrays, slicing with a single row fails.

**Comment by javicid** [comment]
> Also, for sparse arrays, slicing with a single row fails.

Is this the same bug or a different one?

**Comment by salvisolamartinell** [comment]
> > Also, for sparse arrays, slicing with a single row fails.
> 
> @salvisolamartinell Is this the same bug or a different one?

Looks like a different bug

**Comment by javicid** [comment]
@salvisolamartinell can you then create a new issue explaining the bug?

**Comment by salvisolamartinell** [comment]
Done: #249
