### ISSUE TITLE
Consider using pandas load_csv instead of numpy loadtxt in data/base.py

### ISSUE THREAD

**Issue by javicid** [bsc-wdc/dislib#29]
According to this http://akuederle.com/stop-using-numpy-loadtxt pandas load_csv is much faster than numpy.

**Comment by nihadness** [comment]
Actually, [this article](http://wesmckinney.com/blog/a-new-high-performance-memory-efficient-file-parser-engine-for-pandas/) says (not directly and 100%, but my conclusions were like that) Panda is faster but it is **still** less memory efficient (can reach 5+ times of file size). I don't know how big the files of 'dislib' algorithms usually are, but I suggest to take into account the memory consumption before replacing everything with Panda's.

**Comment by javicid** [comment]
Thank you, I think we should stay with np.array for the moment. I'm closing the issue.
