### ISSUE TITLE
extension of ds_array creation

### ISSUE THREAD

**Issue by rosabadia** [bsc-wdc/dislib#295]
**Is your feature request related to a problem? Please describe.**
I would like to be able to assign a value to an initialized array.  For example, imagine I have an array initialized to zero, and I want the first element to be 1. 

**Describe the solution you'd like**
I would like the possibility of assigning a value to an element of a ds-array. 

**Describe alternatives you've considered**
What I am currently doing: 
z = np.zeros(size, dtype=np.complex64)
z[0]=1
y = ds.array(z, block_size=(1,4))

And I would like to:

y = ds.zeros(size, block_size=(1,4), dtype=np.complex64)
y[0] = 1

**Additional context**

**Comment by javicid** [comment]
Closed by #297, which implements setting values in ds-arrays
