### ISSUE TITLE
Test fails with updated dependencies 

### ISSUE THREAD

**Issue by salvisolamartinell** [bsc-wdc/dislib#310]
**Describe the bug**
Tests fail in DBSCAN test with Python 3.8 and updated libraries.

**To Reproduce**
./run_tests.sh

**Environment (please complete the following information):**
 - OS: [e.g. linux mint]
 - Version [e.g. 18]
 - COMPSs version 2.7.rc2009 
 - Dislib version 0.5
 -  Python versions 3.8

**Comment by salvisolamartinell** [comment]
[job223_NEW.out.txt](https://github.com/bsc-wdc/dislib/files/5298442/job223_NEW.out.txt)
[job223_NEW.err.txt](https://github.com/bsc-wdc/dislib/files/5298444/job223_NEW.err.txt)

**Comment by salvisolamartinell** [comment]
argon2-cffi==20.1.0
async-generator==1.10
attrs==20.2.0
auto-sklearn==0.10.0
backcall==0.2.0
bleach==3.2.1
cassandra-driver==3.24.0
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
click==7.1.2
cloudpickle==1.6.0
codecov==2.1.9
ConfigSpace==0.4.15
coverage==5.3
cvxpy==1.1.5
cycler==0.10.0
Cython==0.29.21
dask==2.28.0
dbus-python==1.2.16
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.2
dislib==0.5.0
distributed==2.28.0
distro-info===0.23ubuntu1
docutils==0.16
ecos==2.0.7.post1
entrypoints==0.3
flake8==3.8.3
future==0.18.2
geomet==0.2.1.post1
HeapDict==1.0.1
Hecuba==0.1.3.post1
idna==2.8
ipykernel==5.3.4
ipython==7.18.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.2
Jinja2==2.11.2
joblib==0.16.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.7
jupyter-console==6.2.0
jupyter-core==4.6.3
jupyterlab-pygments==0.1.1
kiwisolver==1.2.0
lazy-import==0.2.2
liac-arff==2.5.0
lockfile==0.12.2
MarkupSafe==1.1.1
matplotlib==3.3.2
mccabe==0.6.1
mistune==0.8.4
msgpack==1.0.0
nbclient==0.5.0
nbconvert==6.0.6
nbformat==5.0.7
nest-asyncio==1.4.1
notebook==6.1.4
numpy==1.19.2
osqp==0.6.1
packaging==20.4
pandas==0.25.3
pandocfilters==1.4.2
parameterized==0.7.4
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
prometheus-client==0.8.0
prompt-toolkit==3.0.7
psutil==5.7.2
ptyprocess==0.6.0
pycodestyle==2.6.0
pycparser==2.20
pydevd-pycharm==201.6668.115
pyflakes==2.2.0
Pygments==2.7.1
PyGObject==3.36.0
pynisher==0.6.0
pyparsing==2.4.7
pyrfr==0.8.0
pyrsistent==0.17.3
python-apt==2.0.0+ubuntu0.20.4.1
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
pyzmq==19.0.2
qtconsole==4.7.7
QtPy==1.9.0
requests==2.22.0
requests-unixsocket==0.2.0
scikit-learn==0.22.2.post1
scipy==1.5.2
scs==2.1.2
Send2Trash==1.5.0
six==1.14.0
smac==0.13.0
sortedcontainers==2.2.2
tblib==1.7.0
terminado==0.9.1
testpath==0.4.4
threadpoolctl==2.1.0
toolz==0.11.1
tornado==6.0.4
traitlets==5.0.4
unattended-upgrades==0.1
urllib3==1.25.8
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
zict==2.0.0

**Comment by cTatu** [comment]
Error solved probably by updating scipy/numpy
