### ISSUE TITLE
Kronecker product test taking too long

### ISSUE THREAD

**Issue by salvisolamartinell** [bsc-wdc/dislib#317]
**Describe the bug**
The kronecker product test MathTest.test_kron_0 sometimes takes very long (~1 hour) and makes the travis-ci build fail.

**To Reproduce**
Run the tests on the docker image, multiple times. I've seen it taking ~1 hour on my computer. Looking at the COMPSs temp files, there were around 30.000 files and it kept changing (so apparently many tasks were being run). This may be some issue with the test, because it has a random seed, or an issue with the kronecker product algorithm itself. 

**Expected behavior**
The test should pass in < 10 min (travis-ci time limit without outputs).

**Environment (please complete the following information):**
 - dislib latest docker image

**Comment by salvisolamartinell** [comment]
I have added some prints to track this problem because I couldn't reproduce it locally, but it happened in travis-ci and also happens in Jenkins.

**Comment by cTatu** [comment]
The tests are no longer that slow, maybe it was something related with the COMPSs version
