### ISSUE TITLE
dislib cannot be upgraded via pip install --upgrade

### ISSUE THREAD

**Issue by aiq-kgielow** [bsc-wdc/dislib#411]
**Describe the bug**
Upgrading the dislib package using `pip install --upgrade` gives the following error:

```
Collecting dislib
  Downloading dislib-0.7.0.tar.gz (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.2/121.2 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ft/sq0_hf954xs_slqd0x33pmw80000gn/T/pip-install-4d0vy7ze/dislib_406ac187dff34c8ba791f0923dc263a1/setup.py", line 13, in <module>
          version=open('VERSION').read().strip(),
      FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**To Reproduce**
Either provide steps to reproduce the behavior. Or attach a minimal working example.

Steps:

1. Create a new virtual environment using `poetry venv`
2. Run `poetry run python -m pip install --upgrade dislib`

**Expected behavior**
Expected that upgrading dislib via `pip install --upgrade` works without errors.

**Environment (please complete the following information):**
 - OS: MacOS
 - Version Monterey
 - Dislib version 0.7.0
 - Python version 3.9.13

**Additional context**
I'm using poetry and pyenv to set up my virtual environment.  I have Python 3.9.13 set as my project-specific (local) version.

**Comment by aiq-kgielow** [comment]
The issue persists in 0.7.1 as well

**Comment by cTatu** [comment]
Hello,

Thank you for pointing it out. There was indeed a problem with the package creation.
Now should be resolved.
