### ISSUE TITLE
Whether to use Dataset and unify the signatures for predict, predict_proba, score...

### ISSUE THREAD

**Issue by salvisolamartinell** [bsc-wdc/dislib#66]
For **predict**, we have to decide whether to use Dataset (and fill the labels) or to return just the labels. If the later, all labels together or distributed?
For **predict_proba**, we have to decide whether to use Dataset (and fill the labels with the probabilities 2d array) or just return the probabilities. If the later, all probabilities together or distributed?
For **score**, should we use Datasets?

**Comment by javicid** [comment]
Related to #76

**Comment by javicid** [comment]
As discussed in #76, I think predict_proba should fill the labels with a probability.

score returns a single float, so I don't think there is any problem here.

**Comment by javicid** [comment]
This will be solved in #105
