### ISSUE TITLE
Take advantage of support for collections

### ISSUE THREAD

**Issue by javicid** [bsc-wdc/dislib#73]
List here the parts of the code that can be improved once PyCOMPSs provides support for collections (edit this comment as necessary):

- The ALS algorithm could use the support for collections to avoid reconstructing the U/M matrix in the master side and instead pass the list of rows (future objects) directly to the next tasks.

- A variable number of OUT parameters would improve the performance of as_grid and shuffle. In the case of as_grid, out collections would prevent passing the whole dataset to a single task. In the case of shuffle, out collections would significantly reduce the number of tasks generated.

- IN collections can be used to pass 2 lists to _train task in C-SVM

**Comment by javicid** [comment]
Support for collections is necessary for #75

**Comment by kafkasl** [comment]
The ALS algorithm could use the support for collections to avoid reconstructing the U/M matrix in the master side and instead pass the list of rows (future objects) directly to the next tasks.

**Comment by javicid** [comment]
A variable number of OUT parameters would improve the performance of as_grid and shuffle. In the case of as_grid, out collections would prevent passing the whole dataset to a single task. In the case of shuffle, out collections would significantly reduce the number of tasks generated.

**Comment by javicid** [comment]
IN collections can be used to pass 2 lists to _train task in C-SVM
