### ISSUE TITLE
Decide fit methods behavior with respect to labels

### ISSUE THREAD

**Issue by javicid** [bsc-wdc/dislib#76]
We should decide if 'fit' methods in clustering algorithms set the Dataset labels or not

This is related to #75

**Comment by javicid** [comment]
I have been thinking the following policy:

Always provide fit, fit_predict and predict. Fit does not set the labels, whereas fit_predict and predict do. Then, we could provide Dataset.labels and Dataset.samples to collect all labels and samples.

What do you think @salvisolamartinell @kafkasl ?

**Comment by kafkasl** [comment]
Sounds good to me. Dataset.labels and Dataset.samples can be defined as `@property` so they are methods but can be accessed as members.

**Comment by salvisolamartinell** [comment]
Sounds good.

**Comment by javicid** [comment]
Ok, I'll close this issue then
