### ISSUE TITLE
Tests description

### ISSUE THREAD

**Issue by kafkasl** [bsc-wdc/dislib#78]
Maybe it would be useful to add a line or short comment in the test cases in order to avoid forgetting what they do (nothing too fancy, more like a reminder). Best-effort style no required though. What do you think? @javicid @salvisolamartinell ?

If you agree, we should decide a format or something to make them all consistent.

**Comment by javicid** [comment]
Maybe just a sentence at the beginning of the function? Using triple quotation marks? """

**Comment by kafkasl** [comment]
Ok for me. Like this?
```
    def test_make_classification(self):
        """
        This case checks that .....
        """

```

**Comment by javicid** [comment]
Yes

**Comment by salvisolamartinell** [comment]
Em sembla bé.

**Comment by kafkasl** [comment]
@javicid @salvisolamartinell I've noticed that if the description is a single line, it appears instead of the name during the tests execution. However if they have more than 1 line it gets cut.
i.e., `Tests that min_features and max_features correctly return min ... ok` 
So whenever possible we can try to write a single line (but do not suggest to make it shorter if it means it will have less information a be harder to understand).
