### ISSUE TITLE
Docs: Add a quickstart guide

### ISSUE THREAD

**Issue by javicid** [bsc-wdc/dislib#91]

**Comment by javicid** [comment]
I'm thinking that we could remove the quickstart guide from github and have it in readthedocs.

**Comment by kafkasl** [comment]
I strongly advise against that. I have used a lot and contributed to some OSS projects and I have (almost) never ended up using their documentation (even less for a quickstart). However, I do remember well and fondly the projects that had a great quickstart in github so you don't need to start digging around. Just clone, follow the guide and you are already set.

**Comment by kafkasl** [comment]
Because with these projects you know that you can do pip install and everything will work out of the box always. That is not going to be the case of dislib never because it depends on COMPSs and it's not going to be installable and ready-to-use with a simple pip install.

**Comment by javicid** [comment]
If we provide a pip package, users won't need to access the source code even if they need to install COMPSs.

I think that the important question is "which should be the entry point of the library?", and I think the documentation is a much user-friendly entry point than the Github page (just like in scikit-learn). We could keep the quickstart here as well, but then we would have to maintain 2 separate guides.
