### ISSUE TITLE
CascadeSVM fit() alters the dataset samples

### ISSUE THREAD

**Issue by salvisolamartinell** [bsc-wdc/dislib#97]
When executing classifier_comparision.py, after the fit() call of CascadeSVM estimator the number of samples (and labels) of each Subset changes from 20 to something like 59 or 60. The predictions of the following predictors seem correct so it looks like it could be duplicate samples.

**Comment by javicid** [comment]
@salvisolamartinell Does this happen using PyCOMPSs or by running the program sequentially?

**Comment by salvisolamartinell** [comment]
@javicid Only sequentially.
